apiVersion: v1
kind: PersistentVolume
metadata:
  name: prd-pv
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /backup/data/prod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
