apiVersion: v1
kind: PersistentVolume
metadata:
  name: tst-pv
  namespace: tst
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /backup/data/test
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
