apiVersion: v1
kind: PersistentVolume
metadata:
  name: petclinic-prd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /backup/data/prd
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
