---
- name: Create directories and set permissions on worker nodes
  hosts: workers
  become: true
  tasks:

    - name: Ensure /backup/sonarqube directory exists
      file:
        path: /backup/data/sonarqube
        state: directory
        mode: '0777'
        owner: '1000'
        group: '1000'

    - name: Ensure /backup/nexus directory exists
      file:
        path: /backup/data/nexus
        state: directory
        mode: '0770'
        owner: '200'
        group: '200'


    - name: Ensure /backup/sonarqube-postgresql directory exists
      file:
        path: /backup/data/sonarqube-postgresql
        state: directory
        mode: '0775'  # Set initial permissions
        owner: '1001' # Set owner
        group: '1001' # Set group


    - name: Ensure /backup/data/postgresql directory exists
      file:
        path: /backup/data/postgresql
        state: directory
        mode: '0777'
        owner: '1000'
        group: '1000'
        
        
    - name: Ensure /backup/data/prd directory exists
      file:
        path: /backup/data/prd
        state: directory
        mode: '0777'
        owner: '1000'
        group: '1000'    
        
        
    - name: Ensure /backup/data/dev directory exists
      file:
        path: /backup/data/dev
        state: directory
        mode: '0777'
        owner: '1000'
        group: '1000'   
        
    - name: Ensure /backup/data/test directory exists
      file:
        path: /backup/data/test
        state: directory
        mode: '0777'
        owner: '1000'
        group: '1000'  
        
    - name: Ensure /backup/data/prod directory exists
      file:
        path: /backup/data/prod
        state: directory
        mode: '0777'
        owner: '1000'
        group: '1000'         