---
trigger:
  branches:
    include: [main]
pr:
  branches:
    include: ['*']
pool:
  vmImage: ubuntu-latest
stages:
  - stage: PR
    displayName: PR
    # condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: PR
        displayName: PR Validation Jobs
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: pom.xml
              options: -DskipTests
              publishJUnitResults: false
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.17
              mavenVersionOption: Default
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: Docker@2
            inputs:
              containerRegistry: DockerHub
              repository: mahmoudk1000/petclinic
              command: buildAndPush
              Dockerfile: '**/Dockerfile'
              tags: latest
